function apply_nature_axes(ax)
%APPLY_NATURE_AXES Apply compact journal-style axes formatting.
if nargin < 1 || isempty(ax)
    ax = gca;
end

set(ax, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9, ...
    'LineWidth', 0.75, ...
    'Box', 'on', ...
    'TickDir', 'in', ...
    'TickLength', [0.014 0.014], ...
    'XMinorTick', 'on', ...
    'YMinorTick', 'on', ...
    'Layer', 'top', ...
    'GridLineStyle', '-', ...
    'MinorGridLineStyle', ':', ...
    'GridAlpha', 0.18, ...
    'MinorGridAlpha', 0.12);
grid(ax, 'on');
ax.XColor = [0.10 0.10 0.10];
ax.YColor = [0.10 0.10 0.10];
end
