function task_si_sweep_5methods()
% =========================================================================
% task_si_sweep_5methods
% -------------------------------------------------------------------------
% Five algorithm comparison, angle RMSE only:
%   1. ZF (no SIC)
%   2. Null-space (no SIC)
%   3. Lagrange (no SIC)
%   4. Null-space + digital SIC (LS-estimated SI channel)
%   5. Lagrange + digital SIC (LS-estimated SI channel)
%
% Two sweeps are produced:
%   (A) x = number of receive antennas Mrx, fixed Ns = 3168
%   (B) x = number of subcarriers Ns,      fixed Mrx = 16
%
% Fixed settings: SNR = 0 dB, beta_SI = 10, L = 256, K_stream = 2.
% MC default is 30; increase to 50/100 on the server if time permits.
%
% Outputs:
%   fig/fig_angle_rmse_vs_mrx_5methods_si_sic.fig/.png/.eps
%   fig/fig_angle_rmse_vs_ns_5methods_si_sic.fig/.png/.eps
%   data_angle_rmse_vs_mrx_5methods_si_sic.csv
%   data_angle_rmse_vs_ns_5methods_si_sic.csv
%   task_si_sweep_5methods_mrx.mat
%   task_si_sweep_5methods_ns.mat
%
% NOTE: .fig files are generated by MATLAB itself (not Python), so they
% remain valid MATLAB figure files.
% =========================================================================
t_all = tic;
warning('off','all');

% ======================= 0. Log ==========================================
log_path = fullfile(pwd, 'task_si_sweep_5methods_run.log');
diary(log_path);
diary on;

fprintf('============================================================\n');
fprintf('  task_si_sweep_5methods : Mrx sweep + Ns sweep\n');
fprintf('  Methods: ZF | Null-space | Lagrange | NS+SIC | Lag+SIC\n');
fprintf('  Start: %s\n', char(datetime('now')));

% ======================= 1. Config =======================================
n_mc         = 30;          % Monte Carlo trials per point
snr_fixed    = 0;           % fixed input SNR (dB)
beta_SI_val  = 10;          % strong SI, same as task_si_suppression.m
L_val        = 256;         % OFDM symbols / CPI length
K_stream     = 2;

% (A) Receive-antenna sweep. Use the actual aggregated-equivalent Ns from
%     build_default_params (4 x 3168 = 12672).
Mrx_list     = [4, 16, 36, 64];
Mrx_dim      = [2, 4, 6, 8];       % square URA dimension
n_mrx        = numel(Mrx_list);
Ns_fixed_mrx = 12672;

% (B) Subcarrier sweep. Keep Mrx fixed at 16 (4x4), as task_si_suppression.
%     Include the actual aggregated-equivalent subcarrier count 12672.
Ns_list      = [512, 1024, 2048, 3168, 6336, 12672];
n_ns         = numel(Ns_list);
Mrx_fixed_ns = 16;
Mrx_dim_ns   = 4;

methods = struct( ...
    'tag',      {'zf', 'nullspace', 'lagrange', 'nullspace_sic', 'lagrange_sic'}, ...
    'label',    {'ZF (no SIC)', 'Null-space', 'Lagrange', ...
                 'Null-space + digital SIC', 'Lagrange + digital SIC'}, ...
    'precoder', {'zf', 'nullspace', 'lagrange', 'nullspace', 'lagrange'}, ...
    'use_sic',  {false, false, false, true, true});
n_methods = numel(methods);

fprintf('  SNR=%+d dB | beta_SI=%g | L=%d | K_stream=%d | MC=%d\n', ...
    snr_fixed, beta_SI_val, L_val, K_stream, n_mc);
fprintf('  Mrx sweep: %s (Ns fixed = %d)\n', mat2str(Mrx_list), Ns_fixed_mrx);
fprintf('  Ns sweep : %s (Mrx fixed = %d)\n', mat2str(Ns_list), Mrx_fixed_ns);
fprintf('  Total trials: %d + %d = %d\n', ...
    n_methods*n_mrx*n_mc, n_methods*n_ns*n_mc, ...
    n_methods*(n_mrx+n_ns)*n_mc);
fprintf('============================================================\n\n');

% Reproducible per-trial seeds.
rng(20260825);
rng_seeds_mrx = randi(2^31-1, n_methods, n_mrx, n_mc);
rng_seeds_ns  = randi(2^31-1, n_methods, n_ns,  n_mc);

% ======================= 2. Base parameters ===============================
fprintf('--- Base parameters ---\n');
baseParams = build_default_params();
baseParams.theta_true = [24.63, 15.94];
baseParams.phi_true   = [30.99, 13.58];
baseParams.R_true     = [200.6, 210.4];
baseParams.v_true     = [15.1, -5.4];
baseParams.alpha      = [1.0, 0.8];

baseParams.enable_SI  = true;
baseParams.beta_SI    = beta_SI_val;
baseParams.enable_SIC = false;       % overridden per method below
baseParams.sic_use_true_channel = false;
baseParams.SIC_pilot_len = 64;

baseParams.K          = L_val;
baseParams.K_stream   = K_stream;
baseParams.SNR        = snr_fixed;
baseParams.user_theta_rad = deg2rad(baseParams.theta_true(:));
baseParams.user_phi_rad   = deg2rad(baseParams.phi_true(:));
baseParams.fast_estimator.n_samp_l = min(64, max(8, floor(L_val/2)));
baseParams.fast_estimator.R_max_gate = 600;   % filter SI coherent peak at R=Rmax

Nt_total = baseParams.Ntx * baseParams.Nty;
fprintf('  Ntx=%d (Tx URA %dx%d), Ns_base=%d, B_base=%.1f MHz\n', ...
    Nt_total, baseParams.Ntx, baseParams.Nty, baseParams.N, baseParams.B/1e6);

% ---- Fixed SIC pilot (same for all trials, as in the SIC.m concept) ----
rng(20260826);
if exist('qammod', 'file') == 2
    SIC_pilot = qammod(randi([0 15], Nt_total, 64), 16, 'UnitAveragePower', true);
else
    SIC_pilot = (randn(Nt_total, 64) + 1j*randn(Nt_total, 64)) / sqrt(2);
end
baseParams.SIC_pilot = SIC_pilot;

% ---- H_SI per receive-array size; the same matrix is used for the
%      precoder design and for SI injection / digital SIC. This keeps the
%      comparison fair and prevents the nullspace/Lagrange precoders from
%      being designed for a different SI channel than the one injected.
H_SI_rx_mrx = cell(1, n_mrx);
for mi = 1:n_mrx
    H_SI_rx_mrx{mi} = local_hsi(Nt_total, Mrx_list(mi), ...
        Mrx_dim(mi), Mrx_dim(mi), 20261000 + mi, ...
        baseParams.theta_SI, baseParams.phi_SI);
end

% Fixed 16-RX H_SI for the Ns sweep.
H_SI_rx_16 = local_hsi(Nt_total, Mrx_fixed_ns, Mrx_dim_ns, Mrx_dim_ns, ...
    20260831, baseParams.theta_SI, baseParams.phi_SI);

% ======================= 3. Result arrays =================================
rmse_theta_mrx = NaN(n_methods, n_mrx, n_mc);
rmse_theta_ns  = NaN(n_methods, n_ns,  n_mc);

% ======================= 4A. Mrx sweep ===================================
fprintf('\n==== (A) Mrx sweep: Ns fixed = %d ====\n', Ns_fixed_mrx);

for mi = 1:n_methods
    method = methods(mi);
    fprintf('\n== Method %d/%d: %s ==\n', mi, n_methods, method.label);

    for mrx_i = 1:n_mrx
        Mrx_val = Mrx_list(mrx_i);
        Mv = Mrx_dim(mrx_i);

        % Generate TX for this (method, Mrx) pair using the same H_SI that
        % will be used for SI injection / SIC.
        p_tx = baseParams;
        p_tx.N  = Ns_fixed_mrx;
        p_tx.B  = Ns_fixed_mrx * 120e3;
        p_tx.meta.range_resolution = p_tx.c / (2 * p_tx.B);
        p_tx.joint_fft_3d.Nr = Ns_fixed_mrx;
        p_tx.precoder_type = method.precoder;
        p_tx.H_SI = H_SI_rx_mrx{mrx_i};
        p_tx.enable_SIC = method.use_sic;

        rng(20260000 + mi*100 + mrx_i);
        tx  = generate_mimo_ofdm_waveform(p_tx);
        X_tx = tx.X;
        clear tx;

        p = p_tx;
        p.Mx = Mv;
        p.My = Mv;
        p.joint_fft_3d.Na_x = Mv;
        p.joint_fft_3d.Na_y = Mv;
        p.H_SI_matrix = H_SI_rx_mrx{mrx_i};
        p.enable_SIC  = method.use_sic;
        p.enable_SI   = true;
        p.SNR         = snr_fixed;

        fprintf('  Mrx=%2d | TX: [%dx%dx%dx%d] ', Mrx_val, ...
            size(X_tx,1), size(X_tx,2), size(X_tx,3), size(X_tx,4));

        tt = NaN(1, n_mc);
        t_pt = tic;
        for mc_i = 1:n_mc
            rng(rng_seeds_mrx(mi, mrx_i, mc_i));
            try
                rxCube = simulate_radar_channel_3d(X_tx, p);
                [th, ph, R_est, v_est, ~] = joint_estimator_fast(rxCube, X_tx, p);
                cmp = evaluate_estimation(th, ph, R_est, v_est, p, false);
                clear rxCube th ph R_est v_est;
                if isfield(cmp, 'rmse_theta') && ~isnan(cmp.rmse_theta)
                    tt(mc_i) = cmp.rmse_theta;
                end
                clear cmp;
            catch ME
                clear rxCube th ph R_est v_est cmp;
            end
            if mod(mc_i, 20) == 0, fprintf('.'); end
        end
        rmse_theta_mrx(mi, mrx_i, :) = tt;
        el = toc(t_pt);
        fprintf(' | th=%.4f deg | NaN:%d/%d | %s\n', ...
            median(tt, 'omitnan'), sum(isnan(tt)), n_mc, ...
            duration(0,0,round(el),'Format','mm:ss'));

        clear X_tx;

        save('task_si_sweep_5methods_mrx_checkpoint.mat', ...
            'Mrx_list', 'Ns_fixed_mrx', 'methods', 'n_mc', ...
            'rmse_theta_mrx');
    end
end

% ======================= 4B. Ns sweep ====================================
fprintf('\n==== (B) Ns sweep: Mrx fixed = %d ====\n', Mrx_fixed_ns);

for ni = 1:n_ns
    Ns_val = Ns_list(ni);
    fprintf('\n== Ns=%d ==\n', Ns_val);

    p_base_ns = baseParams;
    p_base_ns.N  = Ns_val;
    p_base_ns.B  = Ns_val * 120e3;
    p_base_ns.meta.range_resolution = p_base_ns.c / (2 * p_base_ns.B);
    p_base_ns.joint_fft_3d.Nr = Ns_val;
    p_base_ns.Mx = Mrx_dim_ns;
    p_base_ns.My = Mrx_dim_ns;
    p_base_ns.joint_fft_3d.Na_x = Mrx_dim_ns;
    p_base_ns.joint_fft_3d.Na_y = Mrx_dim_ns;
    p_base_ns.H_SI = H_SI_rx_16;                % same H_SI for precoder and SIC
    p_base_ns.H_SI_matrix = H_SI_rx_16;

    for mi = 1:n_methods
        method = methods(mi);

        p_tx = p_base_ns;
        p_tx.precoder_type = method.precoder;
        p_tx.enable_SIC = method.use_sic;

        rng(20270000 + ni*10 + mi);
        tx  = generate_mimo_ofdm_waveform(p_tx);
        X_tx = tx.X;
        clear tx;

        p = p_tx;
        p.H_SI_matrix = H_SI_rx_16;
        p.enable_SIC  = method.use_sic;
        p.enable_SI   = true;
        p.SNR         = snr_fixed;

        tt = NaN(1, n_mc);
        t_pt = tic;
        for mc_i = 1:n_mc
            rng(rng_seeds_ns(mi, ni, mc_i));
            try
                rxCube = simulate_radar_channel_3d(X_tx, p);
                [th, ph, R_est, v_est, ~] = joint_estimator_fast(rxCube, X_tx, p);
                cmp = evaluate_estimation(th, ph, R_est, v_est, p, false);
                clear rxCube th ph R_est v_est;
                if isfield(cmp, 'rmse_theta') && ~isnan(cmp.rmse_theta)
                    tt(mc_i) = cmp.rmse_theta;
                end
                clear cmp;
            catch ME
                clear rxCube th ph R_est v_est cmp;
            end
            if mod(mc_i, 20) == 0, fprintf('.'); end
        end
        rmse_theta_ns(mi, ni, :) = tt;
        el = toc(t_pt);
        fprintf('  %-28s | th=%.4f deg | NaN:%d/%d | %s\n', ...
            method.label, median(tt, 'omitnan'), sum(isnan(tt)), n_mc, ...
            duration(0,0,round(el),'Format','mm:ss'));
    end

    save('task_si_sweep_5methods_ns_checkpoint.mat', ...
        'Ns_list', 'Mrx_fixed_ns', 'methods', 'n_mc', ...
        'rmse_theta_ns');
end

fprintf('\nTotal simulation: %.1f min\n', toc(t_all)/60);

% ======================= 5. Summaries and data files ======================
rmse_theta_mrx_med = median(rmse_theta_mrx, 3, 'omitnan');
rmse_theta_ns_med  = median(rmse_theta_ns,  3, 'omitnan');

print_summary('Mrx', Mrx_list, rmse_theta_mrx_med, methods);
print_summary('Ns',  Ns_list,  rmse_theta_ns_med,  methods);

csv_mrx = [Mrx_list(:), rmse_theta_mrx_med'];
csv_ns  = [Ns_list(:),  rmse_theta_ns_med'];
csv_header = {'x', methods.label};

write_csv('data_angle_rmse_vs_mrx_5methods_si_sic.csv', csv_header, csv_mrx);
write_csv('data_angle_rmse_vs_ns_5methods_si_sic.csv',  csv_header, csv_ns);

save('task_si_sweep_5methods_mrx.mat', ...
    'Mrx_list', 'Ns_fixed_mrx', 'methods', 'n_mc', 'snr_fixed', ...
    'beta_SI_val', 'rmse_theta_mrx', 'rmse_theta_mrx_med');
save('task_si_sweep_5methods_ns.mat', ...
    'Ns_list', 'Mrx_fixed_ns', 'methods', 'n_mc', 'snr_fixed', ...
    'beta_SI_val', 'rmse_theta_ns', 'rmse_theta_ns_med');
save('task_si_sweep_5methods.mat', ...
    'Mrx_list', 'Ns_list', 'methods', 'n_mc', 'snr_fixed', ...
    'beta_SI_val', 'rmse_theta_mrx', 'rmse_theta_mrx_med', ...
    'rmse_theta_ns', 'rmse_theta_ns_med');

% ======================= 6. Plot two figures ==============================
labels = {methods.label};

local_plot_sweep( ...
    Mrx_list, rmse_theta_mrx_med, labels, ...
    'Number of receive antennas M_{rx}', ...
    'fig_angle_rmse_vs_mrx_5methods_si_sic', ...
    sprintf('Angle RMSE vs receive antennas (N_s = %d, L = %d, MC = %d)', ...
    Ns_fixed_mrx, L_val, n_mc));

local_plot_sweep( ...
    Ns_list, rmse_theta_ns_med, labels, ...
    'Number of subcarriers N_s', ...
    'fig_angle_rmse_vs_ns_5methods_si_sic', ...
    sprintf('Angle RMSE vs subcarriers (M_{rx} = %d, L = %d, MC = %d)', ...
    Mrx_fixed_ns, L_val, n_mc));

fprintf('\nDone. Total: %.1f min\n', toc(t_all)/60);
diary off;
end

% =========================================================================
% local functions
% =========================================================================
function H = local_hsi(Nt_total, Nr_total, Mx, My, seed, theta_si, phi_si)
hsi_cfg = struct( ...
    'model', 'ura_rician', ...
    'Nt_total', Nt_total, 'Nr_total', Nr_total, ...
    'kappa_SI', 10, ...
    'Ntx', 4, 'Nty', 4, ...
    'Mx', Mx, 'My', My, 'd_lambda', 0.5, ...
    'theta_tx_deg', theta_si, 'phi_tx_deg', phi_si, ...
    'theta_rx_deg', theta_si, 'phi_rx_deg', phi_si, ...
    'seed', seed);
H = generate_HSI(hsi_cfg);
end

function print_summary(name, x, ymed, methods)
fprintf('\n--- Angle RMSE median summary vs %s ---\n', name);
fprintf('%10s', name);
for mi = 1:numel(methods)
    fprintf('  %26s', methods(mi).label);
end
fprintf('\n');
for xi = 1:numel(x)
    fprintf('%10d', x(xi));
    for mi = 1:numel(methods)
        fprintf('  %26.6f', ymed(mi, xi));
    end
    fprintf('\n');
end
end

function write_csv(path, header, data)
fid = fopen(path, 'w');
fprintf(fid, '%s', header{1});
for k = 2:numel(header)
    fprintf(fid, ',%s', header{k});
end
fprintf(fid, '\n');
fclose(fid);
writematrix(data, path, 'WriteMode', 'append');
end

function local_plot_sweep(x, ymed, labels, xlab, fname, title_str)
fig_dir = fullfile(pwd, 'fig');
if ~exist(fig_dir, 'dir'), mkdir(fig_dir); end

colors = {[0.902 0.294 0.208], ...
          [0.302 0.733 0.835], ...
          [0.200 0.627 0.173], ...
          [0.100 0.420 0.750], ...
          [0.100 0.550 0.200]};
markers = {'o', 's', '^', 'd', 'v'};
linestyles = {'-', '--', '-.', ':', ':'};

fig = figure('Color', 'w', 'Units', 'pixels', ...
    'Position', [100, 100, 640, 470]);
hold on;

x = x(:)';
x_dense = linspace(min(x), max(x), 200);

for mi = 1:numel(labels)
    yy = ymed(mi, :);
    valid = isfinite(yy) & (yy > 0);
    if ~any(valid), continue; end

    yy_plot = max(yy(valid), 1e-12);
    xx_plot = x(valid);
    yy_sm = 10.^interp1(xx_plot, log10(yy_plot), x_dense, 'pchip');

    plot(x_dense, yy_sm, ...
        'Color', colors{mi}, 'LineStyle', linestyles{mi}, ...
        'LineWidth', 1.5, 'DisplayName', labels{mi});
    plot(xx_plot, yy_plot, ...
        'Color', colors{mi}, 'LineStyle', 'none', ...
        'Marker', markers{mi}, 'MarkerSize', 7, ...
        'MarkerFaceColor', 'w', 'HandleVisibility', 'off');
end

xlabel(xlab, 'FontName', 'Times New Roman', 'FontSize', 11);
ylabel('Angle RMSE (deg)', 'FontName', 'Times New Roman', 'FontSize', 11);
title(title_str, 'FontName', 'Times New Roman', 'FontSize', 10, ...
    'FontWeight', 'normal');
legend('Location', 'northeast', 'Box', 'on', ...
    'FontName', 'Times New Roman', 'FontSize', 8);

apply_nature_axes(gca);
set(gca, 'YScale', 'log');

xrange = max(x) - min(x);
xlim([min(x) - 0.06*xrange, max(x) + 0.06*xrange]);

yvals = ymed(isfinite(ymed) & (ymed > 0));
if ~isempty(yvals)
    ylo = 10^floor(log10(min(yvals)));
    yhi = 10^ceil(log10(max(yvals)));
    ylim([ylo, yhi]);
    yticks = 10 .^ (floor(log10(ylo)) : ceil(log10(yhi)));
    set(gca, 'YTick', yticks);
    set(gca, 'YTickLabel', ...
        cellfun(@(n) sprintf('10^{%s}', n), ...
        arrayfun(@(v) num2str(log10(v)), yticks, 'UniformOutput', false), ...
        'UniformOutput', false));
end

base = fullfile(fig_dir, fname);
savefig(fig, [base '.fig']);
exportgraphics(fig, [base '.png'], 'Resolution', 300);
print(fig, [base '.eps'], '-depsc2', '-r300');
fprintf('  Saved: %s.fig / .png / .eps\n', base);
end
